install.packages("plotrix")
install.packages("pdfetch")
install.packages("networkD3")
install.packages("knitr")
install.packages("expm")
install.packages("igraph")
source("http://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")

install.packages("C:/Users/ratouis/Desktop/Dossier de travail/R/PKSFC_1.1.tar_.gz", repos = NULL, type="source")
library(PKSFC)
library(Rgraphviz)
library(igraph)
library(expm)
library(Matrix) 