
shinyUI(fluidPage(
  titlePanel("Model GROWTH"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Model description"),
      tabsetPanel(
        tabPanel("Equations", tableOutput("equations")),
        tabPanel("Parameters",fluidPage(
          sliderInput("npl",
                      label = "Non performing loans:",
                      min = 0, max = 1, value = 0.6),
          
          sliderInput("psiD",
                      label = "Share of dividends:",
                      min = 0, max = 1, value = 0.4),
          
          sliderInput("gr0",
                      label = "Animal spirits:",
                      min = 0, max = 1, value = 0.00122),
          
          sliderInput("Nfe",
                      label = "Active Population:",
                      min = 0, max = 100, value = 20),
          
          sliderInput("gr_pr",
                      label = "Growth of Productivity:",
                      min = 0, max = 1, value = 0.03),
          sliderInput("gr_g",
                      label = "Growth of Public Expenditure:",
                      min = -0.1, max =0.1, value = 0.03)
        )),
        tabPanel("DAG", plotOutput("dag"))
      )),
    
    
    mainPanel(
      tabsetPanel(
        tabPanel("Plot",fluidRow(
          column(3,checkboxGroupInput("checkGroup",
                                      label = h3("Variables"),
                                      choices = list("Real output" = "y",
                                                     "Nominal output" = "Y",
                                                     "Real capital stcok" = "k", 
                                                     "Nominal capital stock" = "K",
                                                     "Growth rate of capital (Real)" = "gr_k",
                                                     "Utilization rate" = "u",
                                                     "Real interest rate on loans" = "rrl",
                                                     "Inflation" = "pi",
                                                     "Real gross investment" = "i",
                                                     "Mark-up" = "phi"),
                                      selected = c("y"))),
          column(3,checkboxGroupInput("checkGroup",
                                      label = h3("..."),
                                      choices = list("Planned entrepreneurial profits" = "Ff_T",
                                                     "Realized entrepreneurial profits" = "Ff",
                                                     "Retained earnings" = "FUf", 
                                                     "Distributed profits" = "FDf",
                                                     "Non-performing loans" = "NPL",
                                                     "Employment rate" = "ER",
                                                     "Nominal wage" = "W",
                                                     "Wage bill" = "WB",
                                                     "Productivity" = "pr",
                                                     "Actual unit cost" = "UC"),
                                                      )),
          column(3,checkboxGroupInput("checkGroup",
                                      label = h3("..."),
                                      choices = list("Demand of loans (firms)" = "Lfd",
                                                    "Supply of equity" = "es",
                                                    "Proportion of deposits (households)" = "P1", 
                                                    "Proportion of bills" = "P2",
                                                    "Proportion of bonds" = "P3",
                                                    "Proportion of equity" = "P4",
                                                    "Real stock of wealth" = "v",
                                                    "Real consumption" = "c",
                                                    "Burden of personal debt" = "BUR"),
                                                    )),
          column(3,checkboxGroupInput("checkGroup",
                                      label = h3("..."),
                                      choices = list("Price of equity" = "pe",
                                                     "Capital Adequacy Ratio" = "CAR",
                                                     "Rate on bills" = "rb",
                                                     "Rate on bonds" = "rbl", 
                                                     "Deposit rate" = "rm",
                                                     "Loan rate" = "rl"),
                                                      )),
          column(9, plotOutput("plot"))
        )
        ),
        tabPanel("Plot Scenario",fluidRow(
          column(3,checkboxGroupInput("checkGroup_scen",
                                      label = h3("Variables"),
                                      choices = list("Real output" = "y",
                                                     "Nominal output" = "Y",
                                                     "Real capital stcok" = "k", 
                                                     "Nominal capital stock" = "K",
                                                     "Growth rate of capital (Real)" = "gr_k",
                                                     "Utilization rate" = "u",
                                                     "Real interest rate on loans" = "rrl",
                                                     "Inflation" = "pi",
                                                     "Real gross investment" = "i",
                                                     "Mark-up" = "phi"),
                                      selected = c("y"))),
          column(3,checkboxGroupInput("checkGroup_scen",
                                      label = h3("..."),
                                      choices = list("Planned entrepreneurial profits" = "Ff_T",
                                                     "Realized entrepreneurial profits" = "Ff",
                                                     "Retained earnings" = "FUf", 
                                                     "Distributed profits" = "FDf",
                                                     "Non-performing loans" = "NPL",
                                                     "Employment rate" = "ER",
                                                     "Nominal wage" = "W",
                                                     "Wage bill" = "WB",
                                                     "Productivity" = "pr",
                                                     "Actual unit cost" = "UC"),
                                                      )),
          column(3,checkboxGroupInput("checkGroup_scen",
                                      label = h3("..."),
                                      choices = list("Demand of loans (firms)" = "Lfd",
                                                     "Supply of equity" = "es",
                                                     "Proportion of deposits (households)" = "P1", 
                                                     "Proportion of bills" = "P2",
                                                     "Proportion of bonds" = "P3",
                                                     "Proportion of equity" = "P4",
                                                     "Real stock of wealth" = "v",
                                                     "Real consumption" = "c",
                                                     "Burden of personal debt" = "BUR"),
                                                      )),
          column(3,checkboxGroupInput("checkGroup_scen",
                                      label = h3("..."),
                                      choices = list("Price of equity" = "pe",
                                                     "Capital Adequacy Ratio" = "CAR",
                                                     "Rate on bills" = "rb",
                                                     "Rate on bonds" = "rbl", 
                                                     "Deposit rate" = "rm",
                                                     "Loan rate" = "rl"),
                                                      )),
                 numericInput("init",label = h3("Scenario init"),value = 2020),
                 numericInput("end",label = h3("Scenario end"),value = 2020)),
          column(9, plotOutput("plotscen")),
          column(6,sliderInput("npl_scen",
                               label = "Non Performing loans:",
                               min = 0, max = 1, value = 0.6),
                 
                 sliderInput("psiD_scen",
                             label = "Share of Dividends:",
                             min = 0, max = 1, value = 0.4),
                 sliderInput("gr_g_scen",
                             label = "Growth of Public Expenditure:",
                             min = -0.1, max = 0.1, value = 0.03)),
          column(6,
                 sliderInput("gr0_scen",
                             label = "Animal Spirits:",
                             min = 0, max = 1, value = 0.00122),
                 
                 sliderInput("Nfe_scen",
                             label = "Active Population",
                             min = 0, max = 100, value = 20),
                 
                 sliderInput("gr_pr_scen",
                             label = "Growth of Productivity:",
                             min = 0, max = 1, value = 0.03))
                 
          )
        )
        )
      )
    )
  )
